SELECT AIN.ANIMAL_ID, AIN.ANIMAL_TYPE, AIN.NAME
FROM ANIMAL_INS AS AIN
LEFT JOIN ANIMAL_OUTS AS AOUT ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
WHERE AIN.SEX_UPON_INTAKE LIKE 'Intact%'
    AND (AOUT.SEX_UPON_OUTCOME LIKE 'Spayed%' OR AOUT.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY AIN.ANIMAL_ID